version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nexhire_postgres
    environment:
      POSTGRES_USER: nexhire
      POSTGRES_PASSWORD: nexhire123
      POSTGRES_DB: nexhire_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nexhire']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nexhire_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
